### PR TITLE
Fix "Lock screen" for recent Xubuntu

### PR DESCRIPTION
**Pull request by aeberspaecher**
Instead of invoking the screensaver for locking the screen, the script `xflock4` is called now. This should work on all systems, no matter if they use a screensaver such as xscreensaver or another tool to lock the screen (e.g. lightlocker in Xubuntu 14.04).

### CODE REVIEW

**Comment by pbx** [comment]
FWIW I'm running Xubuntu 16.04 with latest Kupfer, and the stock behavior *does* lock my screen correctly. My Power Manager settings are *not* set to auto-lock the screen on screensaver activation, so it seems [the "lock" param that Kupfer passes to xdg-screensaver](https://github.com/engla/kupfer/blob/04bbd63c483cbefe8230679aa892452fabb77e14/kupfer/plugin/session_xfce.py#L15) (which command is indeed still present in Xfce 16.04) is doing the trick.

**Comment by aeberspaecher** [comment]
Today (on Xubuntu 16.04) I'm actually not sure whether I'm using stock Kupfer or a patched one... My worries have shifted: it's becoming obvious that Kupfer is not maintained any more. As an example, the XFCE settings cannot be reached from Kupfer any longer.

**Comment by engla** [comment]
Hey. Kupfer has been incredibly useful, even though I haven't done anything significant work on it since 2010. I'll post a new port to $CURRENT_YEAR soon, which should make it ready to go into the next decade.

**Comment by engla** [comment]
Kupfer has entered a new decade: https://kupferlauncher.github.io/

With Python 3, Gtk 3, and reindentation, all PRs now need to update. We are also looking for maintainers. Cheers!

**Pull request closed without merging**
