### PR TITLE
 Password Settings not Supported #79

### LINKED ISSUE #79: Password Settings not Supported
Current version can't use plugin_support.UserNamePassword as plugin setting type.

### Actual Behaviour
raise ImportError ["Keyring is not supported"](https://github.com/kupferlauncher/kupfer/blob/master/kupfer/plugin_support.py#L151)

### Expected Behaviour
Maybe use [Keyring](https://pypi.python.org/pypi/keyring) to implement this feature.

### PR DESCRIPTION
**Pull request by hugosenari**
Fix #79 
Add  UserNamePassword again and expose API to plugin define own pass type.
Just because #85 will not solve problem when service only accept OAuth, SAML or any kind of login or define strange config types.

### CODE REVIEW

**Comment by bluss** [comment]
I prefer the other one. ExtendedSetting is in kupfer.core and can not be used by plugins.

I'd also prefer if plugins did not become too entangled with the Gtk interface. As an aside, the best interface for plugins is the “kupfer interface”, i.e. exposing leaves and actions as usual.

**Comment by hugosenari** [comment]
I will see options to implement generic OAuth flow and expose as ExtendedSetting. :)

**Comment by hugosenari** [comment]
I was thinking...
Even if we won't expose ExtendedSetting for plugin, this change is necessary for use of any ExtendedSetting subclass, instead of current code that only apply for UserNamePassword. :-D

**Comment by hugosenari** [comment]
Added OAuth1 to this branch.
I created a [Twitter plugin](https://github.com/hugosenari/Kupfer-Plugins/blob/master/tuiuiu/tuiuiu.py) and some [twitter](https://twitter.com/hugosenari/status/847660445649346562) [posts](https://twitter.com/hugosenari/status/847694779596947457) to test.

Please give some feedback, so I can try add OAuth2 or rethink entire solution. =-)

**Comment by khurshid-alam** [comment]
I would be wonderful to have oauth support in kupfer.

@hugosenari How do I enter my own credentials?

**Comment by hugosenari** [comment]
What you mean as credentials?

__If you talking about 'OAuth Token' as plugin user:__
At plugin preferences:
- Click on 'Set' (opens OAuth Preference Dialog);
- Then in 'Request New Token' (this will open browser asking for auth...);
- Copy & Paste received Token back to OAuth Preference Dialog;
- Click "OK".

In theory we can setup a local http server (using SimpleHttpServer) and receive Token back without copy & paste, but is more code complexity to deal. :-/


__If you need to know how to set Consumer Credentials:__
```
from kupfer.plugin_support import PluginSettings, OAuth1, check_oauth_support
check_oauth_support()
__kupfer_settings__ = PluginSettings( 
    {
        "key" : "oauth",
        "label": _("Access Token"),
        "type": OAuth1,
        "value": OAuth1(
            plugin_id="CONSUMER_CREDENTIALS_GOES_HERE",
            plugin_secret="AND_HERE",
            url_access="https://api.twitter.com/oauth/access_token",
            url_auth="https://api.twitter.com/oauth/authorize",
            url_request="https://api.twitter.com/oauth/request_token",
            url_callback="https://hugosenari.github.io/Kupfer-Plugins/token.html"
        ),
    }
)
```

__Now If what you need is create your own Credentials Config Type:__
As plugin user you can't. ;-)
As plugin developer you  can't (unofficial: extending OAth1 overriding ask_user).
As kupfer developer extend settings.ExtendedSetting (ie: [simple](https://github.com/hugosenari/kupfer/blob/UserNamePassword/kupfer/plugin_support.py#L151), [complex](https://github.com/hugosenari/kupfer/blob/UserNamePassword/kupfer/plugin_support.py#L195))

**Comment by khurshid-alam** [comment]
@hugosenari I see.

So **if this gets merged** as a plugin developer I can use any other services which uses oauth1. Right?

**Comment by hugosenari** [comment]
@khurshid-alam yeah but only 3 legged OAuth 1.0a.
I would appreciate some feedback in this code (even without merge) to start something with OAuth 2.0.

**Pull request closed without merging**
