### PR TITLE
 Password Settings not Supported #79

### LINKED ISSUE #79: Password Settings not Supported
Current version can't use plugin_support.UserNamePassword as plugin setting type.

### Actual Behaviour
raise ImportError ["Keyring is not supported"](https://github.com/kupferlauncher/kupfer/blob/master/kupfer/plugin_support.py#L151)

### Expected Behaviour
Maybe use [Keyring](https://pypi.python.org/pypi/keyring) to implement this feature.

### PR DESCRIPTION
**Pull request by hugosenari**
Add back UserNamePassword
Fix #79

### CODE REVIEW

**Comment by bluss** [comment]
keyring seems to have changed so that it doesn't have an unencrypted fallback. That's a good thing.

**Comment by khurshid-alam** [comment]
@hugosenari How can a plugin developer use this so a user can input password in kupfer plugin settings? Can you please explain?

**Comment by hugosenari** [comment]
@khurshid-alam this is a version 2 feature, I just added old code back.
For user is just a 'login' button at plugin config.
From plugin just add something like this:
```python
__kupfer_settings__ = PluginSettings( 
    {
        "key" : "login",
        "label": "Login",
        "type": UserNamePassword,
        "value": None
})

# and use it:
jira_login = __kupfer_settings__['login'] 
jira_login.username
jira_login.password
```

**Comment by khurshid-alam** [comment]
@bluss  I tested and it works. Could you please merge this? This is important for plugin developers. Thanks.

**Pull request closed without merging**
