### PR TITLE
(re-)add plugins: deepdirectories, virtualbox

### PR DESCRIPTION
**Pull request by thomas-mc-work**
Originally written by Karol Będkowski himself.

Changes:
- deepdirectories: fixed the Python 3 compatibility
- virtualbox: adapted new path to the config file

### CODE REVIEW

**Comment by thomas-mc-work** [comment]
It's a pleasure to see your comment!

You're right, the python APIs aren't working yet because I've only worked on making the CLI API functional again. When looking at the python API I found out that it's missing on my system. I've installed the package `virtualbox-5.2` from the official repo of oracle. The only thing I've found is `/usr/lib/python2.7/dist-packages/vboxapi/VirtualBox_constants.py`. The path is suggesting the Python version support which would be incompatible the the current Kupfer implementation. I guess oracle has moved the API support focus to their XPCOM API.

From my point of view it would be perfectly fine to remove the deprecated python APIs completely from kupfer and only rely upon the CLI interface. Or are there any advantages of them that deserve to be considered? Anyway I think it's better to have limited support instead of no support at all.

**Comment by KarolBedkowski** [comment]
Hi,
I've updated this plugin. API version now work ok. Also I've updated cli/ose version to work with non-ose version.
You can check it here:
https://github.com/KarolBedkowski/kupfer/tree/fix-virtualbox

**Comment by thomas-mc-work** [comment]
Super! Thank you very much. Do you intend to create a Pull Request then? And shall I recreate mine to noly contain the `deepdirectories` PlugIn?

**Comment by thomas-mc-work** [comment]
ping @KarolBedkowski

**Comment by KarolBedkowski** [comment]
Hi, 
Sorry, I miss this comment.
I'll merge this changes in next free moment - maybe in next weekend.
deepdirectories never was a part of official Kupfer. I'm not sure it should be.

**Comment by KarolBedkowski** [comment]
Virtualbox plugins merged in  a1dbcfc.

**Comment by thomas-mc-work** [comment]
@KarolBedkowski: Thank you for merging!

> deepdirectories never was a part of official Kupfer. I'm not sure it should be.

From my point of view this is an excellent extension to kupfer, since it allows me to open files as easy as launching applications. Because of that I'm doing the latter action far less often because an application is only a means of an end (a file or document). After all the extension will be enabled optionally, so no damage to unconscious users. But you have the final say.

I'd create a separate pull request if you agree.

**Comment by khurshid-alam** [comment]
I agree deepdirectory would be a fantastic addition.

**Pull request closed without merging**
