### PR TITLE
Includes MATE as available DE

### PR DESCRIPTION
**Pull request by igorsantos07**
This is an extension to #15

### CODE REVIEW

**Comment by engla** [comment]
Kupfer has entered a new decade: https://kupferlauncher.github.io/

With Python 3, Gtk 3, and reindentation, all PRs now need to update. We are also looking for maintainers. Cheers!

**Comment by igorsantos07** [comment]
Too bad we who are using a (supposedly) LTS release won't be able to
install it x_x


*Igor Santos*
Desenvolvedor web @ Toptal - the top 3% of freelancer talent
<http://www.toptal.com/#obtain-only-eye-opening-coders-now>
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by bluss** [comment]
@igorsantos07 Can you be more detailed, which dependencies are missing for you? Note that kupfer can only fix issues that it knows about.

**Comment by igorsantos07** [comment]
Duh, what a stupid email I sent. Sorry.

I was referring to the PPA
<https://launchpad.net/~webupd8team/+archive/ubuntu/kupfer> not supporting
Xenial, and the release article
<http://www.webupd8.org/2017/02/kupfer-quick-launcher-ported-to-python.html>
citing it can't be ran on Ubuntu 16.04 / Mint 18 because of the newest
dependencies of Kupfer :(

I didn't try building it from scratch, but that quite defeats my desktop
usage (even more for a project during active development) as it's
troublesome to get updates.


*Igor Santos*
Desenvolvedor web @ Toptal - the top 3% of freelancer talent
<http://www.toptal.com/#obtain-only-eye-opening-coders-now>
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by bluss** [comment]
That article is just based on speculation. Read this project's README if you want the details. It says we don't know the minimum requirements, because nobody has reported back.

**Comment by bluss** [comment]
Link https://github.com/kupferlauncher/kupfer#build-requirements

**Comment by igorsantos07** [comment]
What means I should try installing it here and reporting any issues?

Cool, will do!


*Igor Santos*
Desenvolvedor web @ Toptal - the top 3% of freelancer talent
<http://www.toptal.com/#obtain-only-eye-opening-coders-now>
igorsantos.com.br <http://www.igorsantos.com.br>

**Comment by bluss** [comment]
Yes. No guarantee it will work unfortunately, we just don't know. With your results we will know more.

**Pull request closed without merging**
