### PR TITLE
some additional plugins for kupfer

### PR DESCRIPTION
**Pull request by thorko**
this is a plugin to manage kde5 session

### CODE REVIEW

**Comment by SanskritFritz** [comment]
Nice, I tested it, works great.

**Comment by thorko** [comment]
added another plugin to parse vivaldi bookmarks

**Comment by thorko** [comment]
and here comes the old google search plugin which I copied from duckduckgo search

**Comment by thomas-mc-work** [comment]
@KarolBedkowski Can't this be either simply merged or at least commented with a reclamation?

**Comment by KarolBedkowski** [comment]
This is 7y old patch; hard to say is it still working. For sure is not compatible with last Kupfer versions.
We don't need "search with google" - we have "search the web" plugin that can handle also google.
Also each plugin should be separated and updated to work with last version.
New PR welcome.

**Pull request closed without merging**
