### PR TITLE
Take screenshot with Flameshot as a Runnable Leaf

### PR DESCRIPTION
**Pull request by pstuifzand**

### CODE REVIEW

**Comment by KarolBedkowski** [comment]
Not sure, its should be separate plugin as long this may be simple, runable script.
TBD

**Comment by pstuifzand** [comment]
Perhaps this plugin should be expanded with a way to create a screenshot that can used directly in kupfer. Perhaps with image upload or open with application.

**Comment by KarolBedkowski** [comment]
Yes, this may be quite useful - call flameshot (by cli or by dbus) and use result in some action in Kupfer.

**Comment by KarolBedkowski** [comment]
Screenshot plugin was added in v323,

**Pull request closed without merging**
