### PR TITLE
BUG: Firefox plugins: copy places.sqlite to tmp dir before querying

### PR DESCRIPTION
**Pull request by darioseidl**
For a while, the Firefox bookmarks and keywords plugins have stopped working when Firefox was open. Firefox locks the `places.sqlite` database while opened, and Kupfer would fail to query it:

    Exception in [kupfer.plugin.firefox] BookmarksSource: OperationalError: database is locked

This PR copies `places.sqlite` to the tmp directory to fix that.

### CODE REVIEW

**Comment by KarolBedkowski** [comment]
Thanks, but there is simpler method; see: https://github.com/KarolBedkowski/kupfer/commit/3e1ff99ee569f00bcfe67ae392bf1949b93a187f
Please check is this work for you.

**Comment by darioseidl** [comment]
Cool, thanks. That works for me as well, but the [docs](https://www.sqlite.org/c3ref/open.html) warn about opening a sqlite db with `immutable` if it may change. I'm not sure how much of a problem that might be in practice, but copying the file is probably safer.

I also tried to open it in read-only mode with `?mode=ro`, but that doesn't work with a locked db either.

**Comment by KarolBedkowski** [comment]
Well, copying database file during writing may also generate invalid data.
Reading data form places.sqlite should be quite quick and only on demand this should be IMO quite safe. I didn't observed any problems with this solution, but some more test may be required.

**Comment by thomas-mc-work** [comment]
What about a combination of both: `?immutable=1&mode=ro`? That would prevent the said possibly accidental change.

**Comment by KarolBedkowski** [comment]
Well, we know that we only do selects on this database, so there is no changes from kupfer. Adding mode=ro shoudl nothing change, so I added it.

I thing worth is do more that one attempt to open/read database; like this:
https://github.com/KarolBedkowski/kupfer/commit/14f7a7767c90263732e20b54328e9b49896f75f6

**Comment by darioseidl** [comment]
> I thing worth is do more that one attempt to open/read database; like this:
KarolBedkowski@14f7a77

Looks good, I'll give this version a try. Working well so far.

**Comment by bluss** [comment]
Using immutable looks like it should work. Of course it can return errors, since it is not actually immutable, but it's worth a shot.

Reading the documentation, they describe the possible outcomes of it changing anyway https://www.sqlite.org/uri.html

This allays one of the fears I would have - that using it incorrectly could cause crashes or unbounded erratic behaviour — we don't want to crash the whole application. As long as it behaves inside the boundaries of success/error it should be fine.

**Comment by KarolBedkowski** [comment]
After about 2 months I don't see any problems with immutable mode, so I merged this path into upstream.

**Pull request closed without merging**
